//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthClinic.Properties.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštanje.
        /// </summary>
        public static string accommodation {
            get {
                return ResourceManager.GetString("accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o smeštanju.
        /// </summary>
        public static string accommodationInformation {
            get {
                return ResourceManager.GetString("accommodationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena naloga.
        /// </summary>
        public static string accountChange {
            get {
                return ResourceManager.GetString("accountChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivacija naloga.
        /// </summary>
        public static string accountDeactivation {
            get {
                return ResourceManager.GetString("accountDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulacija nalogom.
        /// </summary>
        public static string accountManipulation {
            get {
                return ResourceManager.GetString("accountManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled naloga.
        /// </summary>
        public static string accountReview {
            get {
                return ResourceManager.GetString("accountReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje jezika.
        /// </summary>
        public static string addingLanguage {
            get {
                return ResourceManager.GetString("addingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje teme.
        /// </summary>
        public static string addingTheme {
            get {
                return ResourceManager.GetString("addingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novi jezik.
        /// </summary>
        public static string addLanguage {
            get {
                return ResourceManager.GetString("addLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novu temu.
        /// </summary>
        public static string addNewTheme {
            get {
                return ResourceManager.GetString("addNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa:.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da                      otkažete termin?.
        /// </summary>
        public static string anotherTextInCancelingTerm {
            get {
                return ResourceManager.GetString("anotherTextInCancelingTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmenite podatake koje želite:.
        /// </summary>
        public static string anotherTextInDataModInRecRoom {
            get {
                return ResourceManager.GetString("anotherTextInDataModInRecRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string backToLogIn {
            get {
                return ResourceManager.GetString("backToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovi podaci:.
        /// </summary>
        public static string basicData {
            get {
                return ResourceManager.GetString("basicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po lekarima.
        /// </summary>
        public static string byDoctors {
            get {
                return ResourceManager.GetString("byDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po sobama.
        /// </summary>
        public static string byRooms {
            get {
                return ResourceManager.GetString("byRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazivanje.
        /// </summary>
        public static string canceling {
            get {
                return ResourceManager.GetString("canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni nalog.
        /// </summary>
        public static string changeAccount {
            get {
                return ResourceManager.GetString("changeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni jezik.
        /// </summary>
        public static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promena jezika.
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmenite podatke o pacijentu:.
        /// </summary>
        public static string changePatientData {
            get {
                return ResourceManager.GetString("changePatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promeni temu.
        /// </summary>
        public static string changeTheme {
            get {
                return ResourceManager.GetString("changeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmenite svoje podatke:.
        /// </summary>
        public static string changeYourData {
            get {
                return ResourceManager.GetString("changeYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promena teme.
        /// </summary>
        public static string changingTheme {
            get {
                return ResourceManager.GetString("changingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum odjave:.
        /// </summary>
        public static string checkOutDate {
            get {
                return ResourceManager.GetString("checkOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi datum.
        /// </summary>
        public static string chooseD {
            get {
                return ResourceManager.GetString("chooseD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum.
        /// </summary>
        public static string chooseDate {
            get {
                return ResourceManager.GetString("chooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite doktora.
        /// </summary>
        public static string chooseDoc {
            get {
                return ResourceManager.GetString("chooseDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite lekara:.
        /// </summary>
        public static string chooseDoctor {
            get {
                return ResourceManager.GetString("chooseDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite jezik aplikacije:.
        /// </summary>
        public static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite sobu.
        /// </summary>
        public static string chooseR {
            get {
                return ResourceManager.GetString("chooseR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu:.
        /// </summary>
        public static string chooseRoom {
            get {
                return ResourceManager.GetString("chooseRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite temu aplikacije:.
        /// </summary>
        public static string chooseThemeForApp {
            get {
                return ResourceManager.GetString("chooseThemeForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite vreme.
        /// </summary>
        public static string chooseTime {
            get {
                return ResourceManager.GetString("chooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda identiteta.
        /// </summary>
        public static string confirmationOfIdentity {
            get {
                return ResourceManager.GetString("confirmationOfIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj nalog.
        /// </summary>
        public static string createAccount {
            get {
                return ResourceManager.GetString("createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiranje naloga 1.
        /// </summary>
        public static string creatingAnAccount1 {
            get {
                return ResourceManager.GetString("creatingAnAccount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiranje naloga 2.
        /// </summary>
        public static string creatingAnAccount2 {
            get {
                return ResourceManager.GetString("creatingAnAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        public static string darkTheme {
            get {
                return ResourceManager.GetString("darkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena podataka.
        /// </summary>
        public static string dataModification {
            get {
                return ResourceManager.GetString("dataModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja:.
        /// </summary>
        public static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviraj nalog.
        /// </summary>
        public static string deactivateAccount {
            get {
                return ResourceManager.GetString("deactivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta prikaza:.
        /// </summary>
        public static string displayType {
            get {
                return ResourceManager.GetString("displayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar:.
        /// </summary>
        public static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekari specijalisti.
        /// </summary>
        public static string doctorsSpecialist {
            get {
                return ResourceManager.GetString("doctorsSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termini lekara.
        /// </summary>
        public static string doctorsTerm {
            get {
                return ResourceManager.GetString("doctorsTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejl adresa:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme završetka:.
        /// </summary>
        public static string endTime {
            get {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite adresu.
        /// </summary>
        public static string enterAddress {
            get {
                return ResourceManager.GetString("enterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos podataka.
        /// </summary>
        public static string enterData {
            get {
                return ResourceManager.GetString("enterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite mejl.
        /// </summary>
        public static string enterEmail {
            get {
                return ResourceManager.GetString("enterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite JMBG.
        /// </summary>
        public static string enterJMBG {
            get {
                return ResourceManager.GetString("enterJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime.
        /// </summary>
        public static string enterName {
            get {
                return ResourceManager.GetString("enterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretražite termine.
        /// </summary>
        public static string enterParametarForSearch {
            get {
                return ResourceManager.GetString("enterParametarForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite inicijalnu šifru.
        /// </summary>
        public static string enterPassword {
            get {
                return ResourceManager.GetString("enterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lozinku.
        /// </summary>
        public static string enterPassword2 {
            get {
                return ResourceManager.GetString("enterPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite kontakt tel..
        /// </summary>
        public static string enterPhone {
            get {
                return ResourceManager.GetString("enterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite mesto rođenja.
        /// </summary>
        public static string enterPlaceOfBirth {
            get {
                return ResourceManager.GetString("enterPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite državu.
        /// </summary>
        public static string enterState {
            get {
                return ResourceManager.GetString("enterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite prezime.
        /// </summary>
        public static string enterSurname {
            get {
                return ResourceManager.GetString("enterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime.
        /// </summary>
        public static string enterUsername {
            get {
                return ResourceManager.GetString("enterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string examinations {
            get {
                return ResourceManager.GetString("examinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlazak.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite podatke za kreiranje                          naloga pacijentu:.
        /// </summary>
        public static string fillDataForCreatingAccount {
            get {
                return ResourceManager.GetString("fillDataForCreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaboravljena lozinka?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaboravljena lozinka.
        /// </summary>
        public static string forgotPasswordTitle {
            get {
                return ResourceManager.GetString("forgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slobodni lekari:.
        /// </summary>
        public static string freeDoctor {
            get {
                return ResourceManager.GetString("freeDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slobodne sale:.
        /// </summary>
        public static string freeRoom {
            get {
                return ResourceManager.GetString("freeRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slobodno vreme:.
        /// </summary>
        public static string freeTime {
            get {
                return ResourceManager.GetString("freeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekari opšte prakse.
        /// </summary>
        public static string generalPractitioner {
            get {
                return ResourceManager.GetString("generalPractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izgeneriši.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string giveUp {
            get {
                return ResourceManager.GetString("giveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostujući nalog.
        /// </summary>
        public static string guestAccount {
            get {
                return ResourceManager.GetString("guestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lozinku.
        /// </summary>
        public static string inputPasswordInMainW {
            get {
                return ResourceManager.GetString("inputPasswordInMainW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG pacijenta.
        /// </summary>
        public static string inputPatientJMBG {
            get {
                return ResourceManager.GetString("inputPatientJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime ili JMBG.
        /// </summary>
        public static string inputTextUsernameOrJMBG {
            get {
                return ResourceManager.GetString("inputTextUsernameOrJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime.
        /// </summary>
        public static string inputUsernameInMainW {
            get {
                return ResourceManager.GetString("inputUsernameInMainW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer forme za adresu: Ruma,Iriska 1,Srbija.
        /// </summary>
        public static string invalidAddress {
            get {
                return ResourceManager.GetString("invalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG:.
        /// </summary>
        public static string jmbg {
            get {
                return ResourceManager.GetString("jmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG već postoji!.
        /// </summary>
        public static string jmbgAleadyExsist {
            get {
                return ResourceManager.GetString("jmbgAleadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        public static string lightTheme {
            get {
                return ResourceManager.GetString("lightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje....
        /// </summary>
        public static string loading2 {
            get {
                return ResourceManager.GetString("loading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavljivanje.
        /// </summary>
        public static string logging_in {
            get {
                return ResourceManager.GetString("logging in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moj nalog.
        /// </summary>
        public static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime.
        /// </summary>
        public static string nameAndSurname {
            get {
                return ResourceManager.GetString("nameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        public static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenje.
        /// </summary>
        public static string notificationInLogIn {
            get {
                return ResourceManager.GetString("notificationInLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U redu.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacije.
        /// </summary>
        public static string operations {
            get {
                return ResourceManager.GetString("operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcije manipulacije.
        /// </summary>
        public static string optionManipulation {
            get {
                return ResourceManager.GetString("optionManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostali podaci.
        /// </summary>
        public static string otherData {
            get {
                return ResourceManager.GetString("otherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent:.
        /// </summary>
        public static string patient {
            get {
                return ResourceManager.GetString("patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Već postoji pacijent za uneti JMBG ili korisničko ime!.
        /// </summary>
        public static string patientExists {
            get {
                return ResourceManager.GetString("patientExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime pacijenta.
        /// </summary>
        public static string patientName {
            get {
                return ResourceManager.GetString("patientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        public static string patients {
            get {
                return ResourceManager.GetString("patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validacija pacijenta.
        /// </summary>
        public static string patientValidation {
            get {
                return ResourceManager.GetString("patientValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smesti.
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesto rođenja:.
        /// </summary>
        public static string placeOfBirth {
            get {
                return ResourceManager.GetString("placeOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijem:.
        /// </summary>
        public static string reception {
            get {
                return ResourceManager.GetString("reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oporavak.
        /// </summary>
        public static string recovery {
            get {
                return ResourceManager.GetString("recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj se.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premesti.
        /// </summary>
        public static string relocate {
            get {
                return ResourceManager.GetString("relocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premeštanje.
        /// </summary>
        public static string relocation {
            get {
                return ResourceManager.GetString("relocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled naloga.
        /// </summary>
        public static string reviewAccount {
            get {
                return ResourceManager.GetString("reviewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled obaveštenja:.
        /// </summary>
        public static string reviewNotification {
            get {
                return ResourceManager.GetString("reviewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala:.
        /// </summary>
        public static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale za preglede.
        /// </summary>
        public static string roomsForExaminations {
            get {
                return ResourceManager.GetString("roomsForExaminations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale za oporavak.
        /// </summary>
        public static string roomsForRecovery {
            get {
                return ResourceManager.GetString("roomsForRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale za operacije.
        /// </summary>
        public static string roomsForSurgeries {
            get {
                return ResourceManager.GetString("roomsForSurgeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspored.
        /// </summary>
        public static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazivanje.
        /// </summary>
        public static string scheduling {
            get {
                return ResourceManager.GetString("scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat pretrage.
        /// </summary>
        public static string searchResult {
            get {
                return ResourceManager.GetString("searchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string serbian {
            get {
                return ResourceManager.GetString("serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži.
        /// </summary>
        public static string setUp {
            get {
                return ResourceManager.GetString("setUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava:.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string signOutFromApp {
            get {
                return ResourceManager.GetString("signOutFromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme početka:.
        /// </summary>
        public static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država:.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno ste otkazali termin!.
        /// </summary>
        public static string successfullyCanceling {
            get {
                return ResourceManager.GetString("successfullyCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno ste premestili termin!.
        /// </summary>
        public static string successfullyRelocation {
            get {
                return ResourceManager.GetString("successfullyRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno ste zakazali pregled!.
        /// </summary>
        public static string successfullySchedule {
            get {
                return ResourceManager.GetString("successfullySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak:.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme termina.
        /// </summary>
        public static string termTime {
            get {
                return ResourceManager.GetString("termTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneli ste:.
        /// </summary>
        public static string text1GuestAccount {
            get {
                return ResourceManager.GetString("text1GuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtev za promenu lozinke je uspešno poslat!.
        /// </summary>
        public static string text1InNotificationForPassword {
            get {
                return ResourceManager.GetString("text1InNotificationForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin koji se premešta:.
        /// </summary>
        public static string text1InRelocation {
            get {
                return ResourceManager.GetString("text1InRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneti podatak nije u sistemu,                      napravite gostujući nalog:.
        /// </summary>
        public static string text2GuestAccount {
            get {
                return ResourceManager.GetString("text2GuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatni jezici trenutno ne postoje!.
        /// </summary>
        public static string text2InAddNewLanguage {
            get {
                return ResourceManager.GetString("text2InAddNewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatne teme trenutno ne postoje!.
        /// </summary>
        public static string text2InAddNewTheme {
            get {
                return ResourceManager.GetString("text2InAddNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostavićemo Vam lozinku na email adresu koju ste popunili pri kreiranju naloga..
        /// </summary>
        public static string text2InNotificationForPassword {
            get {
                return ResourceManager.GetString("text2InNotificationForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum u koji želite                      da premestite termin:.
        /// </summary>
        public static string text2InRelocation {
            get {
                return ResourceManager.GetString("text2InRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite potrebne podatke:.
        /// </summary>
        public static string text2InScheduleTerm {
            get {
                return ResourceManager.GetString("text2InScheduleTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAPOMENA: Nijedno polje nije obavezno!.
        /// </summary>
        public static string text2InSearchInOthersRoom {
            get {
                return ResourceManager.GetString("text2InSearchInOthersRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li je ovo pacijent kojeg                           želite da smestite? Ako jeste,                          kliknite &quot;Da&quot; za smeštanje.
        /// </summary>
        public static string textInAccomodationPatient {
            get {
                return ResourceManager.GetString("textInAccomodationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime ili jmbg pacijenta čijim nalogom želite da manipulišete:.
        /// </summary>
        public static string textInAccountManipulation {
            get {
                return ResourceManager.GetString("textInAccountManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označite jezik koji želite da                           dodate:.
        /// </summary>
        public static string textInAddNewLanguage {
            get {
                return ResourceManager.GetString("textInAddNewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označite temu koju želite da                           dodate:.
        /// </summary>
        public static string textInAddNewTheme {
            get {
                return ResourceManager.GetString("textInAddNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin koji se otkazuje:.
        /// </summary>
        public static string textInCancelingTerm {
            get {
                return ResourceManager.GetString("textInCancelingTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li je ovo pacijent kome                      želite da zakažete termin?.
        /// </summary>
        public static string textInConfirmPatientIdentity {
            get {
                return ResourceManager.GetString("textInConfirmPatientIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li je ovo pacijent čijim                      nalogom želite da                          manipulišete?.
        /// </summary>
        public static string textInConfirmPatientIdentityInManipulation {
            get {
                return ResourceManager.GetString("textInConfirmPatientIdentityInManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li je ovo pacijent čiji                           gostujući nalog želite da                          transformišete?.
        /// </summary>
        public static string textInConfirmPatientIdentityInTransformation {
            get {
                return ResourceManager.GetString("textInConfirmPatientIdentityInTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dovršite kreiranje naloga                          pacijentu popunjavanjem                          preostalih podataka:.
        /// </summary>
        public static string textInCreatePatientAccount2 {
            get {
                return ResourceManager.GetString("textInCreatePatientAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o terminu:.
        /// </summary>
        public static string textInDataModInRecRoom {
            get {
                return ResourceManager.GetString("textInDataModInRecRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da                          deaktivirate nalog?.
        /// </summary>
        public static string textInDeactivationPatientAccount {
            get {
                return ResourceManager.GetString("textInDeactivationPatientAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označite po čemu želite da                      prikažete termine:.
        /// </summary>
        public static string textInDisplayType {
            get {
                return ResourceManager.GetString("textInDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite dodatne podatke za                           transformaciju gostujućeg                           naloga u pravi nalog:.
        /// </summary>
        public static string textInFillDataForTransformation {
            get {
                return ResourceManager.GetString("textInFillDataForTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli, Ana.                      Šta želite danas da uradite?.
        /// </summary>
        public static string textInHome {
            get {
                return ResourceManager.GetString("textInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite da se odjavite?.
        /// </summary>
        public static string textInLogoutDialog {
            get {
                return ResourceManager.GetString("textInLogoutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šta želite da uradite?.
        /// </summary>
        public static string textInManipulationOptForSecAcc {
            get {
                return ResourceManager.GetString("textInManipulationOptForSecAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite jednu od ponuđenih                          opcija manipulacije nalogom:.
        /// </summary>
        public static string textInManipulationOptions {
            get {
                return ResourceManager.GetString("textInManipulationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite operaciju nad                           pacijentima:.
        /// </summary>
        public static string textInPatients {
            get {
                return ResourceManager.GetString("textInPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime ili                      JMBG pacijenta kako bi                      proverili da li postoji u                      sistemu:.
        /// </summary>
        public static string textInPatientvalidation {
            get {
                return ResourceManager.GetString("textInPatientvalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime ili                      JMBG pacijenta kojeg želite                      da smestite u salu za                      oporavak:.
        /// </summary>
        public static string textInPatientValidationForRecovery {
            get {
                return ResourceManager.GetString("textInPatientValidationForRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite vreme za novi                      termin:.
        /// </summary>
        public static string textInReloaction2 {
            get {
                return ResourceManager.GetString("textInReloaction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite salu i lekara za novi                      termin:.
        /// </summary>
        public static string textInReloactionTerm3 {
            get {
                return ResourceManager.GetString("textInReloactionTerm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite bilo koji dan iz nedelje                          u kojoj želite da izgnerišete                           nedeljni izveštaj, klikom na:.
        /// </summary>
        public static string textInReport {
            get {
                return ResourceManager.GetString("textInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite datum za pregled                      termina klikom na kalendar:.
        /// </summary>
        public static string textInSchedule {
            get {
                return ResourceManager.GetString("textInSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin koji se zakazuje:.
        /// </summary>
        public static string textInScheduleTerm {
            get {
                return ResourceManager.GetString("textInScheduleTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametri po kojima možete                          da vršite pretragu su:.
        /// </summary>
        public static string textInSearchInOthersRoom {
            get {
                return ResourceManager.GetString("textInSearchInOthersRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite operaciju u podešavanjima:.
        /// </summary>
        public static string textInSettings {
            get {
                return ResourceManager.GetString("textInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite JMBG pacijenta čiji                           gostujući nalog želite da                           transformišete:.
        /// </summary>
        public static string textInTransformationGuestAccount {
            get {
                return ResourceManager.GetString("textInTransformationGuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označite tip doktora za koje želite da vidite termine:.
        /// </summary>
        public static string textInTypeOfDoctors {
            get {
                return ResourceManager.GetString("textInTypeOfDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označite tip sala koje želite                      da vidite:.
        /// </summary>
        public static string textInTypeOfRoom {
            get {
                return ResourceManager.GetString("textInTypeOfRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite Vaše korisničko ime za vraćanje lozinke:.
        /// </summary>
        public static string textInUserControlForgotPassword {
            get {
                return ResourceManager.GetString("textInUserControlForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovni podaci:.
        /// </summary>
        public static string textInViewPatientAccount {
            get {
                return ResourceManager.GetString("textInViewPatientAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možete uneti samo slova i prvo slovo mora biti veliko!.
        /// </summary>
        public static string textWarning2InGuestAccout {
            get {
                return ResourceManager.GetString("textWarning2InGuestAccout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent ne postoji!.
        /// </summary>
        public static string textWarning2InPatValForRec {
            get {
                return ResourceManager.GetString("textWarning2InPatValForRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer validne forme: 063/123-123.
        /// </summary>
        public static string textWarning3InGuestAccount {
            get {
                return ResourceManager.GetString("textWarning3InGuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG mora da sadrži 13 brojeva!.
        /// </summary>
        public static string textWarning4InGuestAccount {
            get {
                return ResourceManager.GetString("textWarning4InGuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate popuniti sva polja!.
        /// </summary>
        public static string textWarningInGuestAccount {
            get {
                return ResourceManager.GetString("textWarningInGuestAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate popuniti ovo polje!.
        /// </summary>
        public static string textWarningInPatientValidation {
            get {
                return ResourceManager.GetString("textWarningInPatientValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektovano vreme je zauzeto!.
        /// </summary>
        public static string textWarningInRelocationTerm2 {
            get {
                return ResourceManager.GetString("textWarningInRelocationTerm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravna lozinka!.
        /// </summary>
        public static string textWarningPasswordInMainW {
            get {
                return ResourceManager.GetString("textWarningPasswordInMainW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravno korisničko ime!.
        /// </summary>
        public static string textWarningUsernameInMainW {
            get {
                return ResourceManager.GetString("textWarningUsernameInMainW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme:.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformiši.
        /// </summary>
        public static string transform {
            get {
                return ResourceManager.GetString("transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformacija.
        /// </summary>
        public static string transformation {
            get {
                return ResourceManager.GetString("transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformiši gostujući.
        /// </summary>
        public static string transformGuest {
            get {
                return ResourceManager.GetString("transformGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrste doktora.
        /// </summary>
        public static string typeOfDoctor {
            get {
                return ResourceManager.GetString("typeOfDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi sala.
        /// </summary>
        public static string typeOfRooms {
            get {
                return ResourceManager.GetString("typeOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime:.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        public static string usernameAlreadyExsist {
            get {
                return ResourceManager.GetString("usernameAlreadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogledaj nalog.
        /// </summary>
        public static string viewAccount {
            get {
                return ResourceManager.GetString("viewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidna adresa!.
        /// </summary>
        public static string warningAddress {
            get {
                return ResourceManager.GetString("warningAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidna mejl adresa!.
        /// </summary>
        public static string warningEmail {
            get {
                return ResourceManager.GetString("warningEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra mora da sadrži najmanje 8 karaktera!.
        /// </summary>
        public static string warningForPassword {
            get {
                return ResourceManager.GetString("warningForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG mora sadržati 13 brojeva!.
        /// </summary>
        public static string warningJMBG {
            get {
                return ResourceManager.GetString("warningJMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvo slovo mora biti veliko!.
        /// </summary>
        public static string warningState {
            get {
                return ResourceManager.GetString("warningState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate da izaberete datum!.
        /// </summary>
        public static string warningTextInReport {
            get {
                return ResourceManager.GetString("warningTextInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime sadrži slova i brojeve!.
        /// </summary>
        public static string warningUsername {
            get {
                return ResourceManager.GetString("warningUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
